package com.dynamodb.model;

import java.util.Date;
import java.util.List;
import java.util.Objects;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "OrderInfo")
public class Order {

    @DynamoDBHashKey
    private String orderId;

    @DynamoDBAttribute
    private String productId;

    @DynamoDBAttribute
    private Integer productQuantity;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Date orderPlacedTimestamp;

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    private Date orderUpdatedTimestamp;

    @DynamoDBIgnore
    private List<OrderItem> items;

    public String getOrderId() {
	return orderId;
    }

    public void setOrderId(String orderId) {
	this.orderId = orderId;
    }

    public String getProductId() {
	return productId;
    }

    public void setProductId(String productId) {
	this.productId = productId;
    }

    public Integer getProductQuantity() {
	return productQuantity;
    }

    public void setProductQuantity(Integer productQuantity) {
	this.productQuantity = productQuantity;
    }

    public String getDescription() {
	return description;
    }

    public void setDescription(String description) {
	this.description = description;
    }

    public Date getOrderPlacedTimestamp() {
	return orderPlacedTimestamp;
    }

    public void setOrderPlacedTimestamp(Date orderPlacedTimestamp) {
	this.orderPlacedTimestamp = orderPlacedTimestamp;
    }

    public Date getOrderUpdatedTimestamp() {
	return orderUpdatedTimestamp;
    }

    public void setOrderUpdatedTimestamp(Date orderUpdatedTimestamp) {
	this.orderUpdatedTimestamp = orderUpdatedTimestamp;
    }

    public List<OrderItem> getItems() {
	return items;
    }

    public void setItems(List<OrderItem> items) {
	this.items = items;
    }

    @Override
    public int hashCode() {
	return Objects.hash(orderId, productId);
    }

    @Override
    public boolean equals(Object obj) {
	if (this == obj)
	    return true;
	if (obj == null)
	    return false;
	if (getClass() != obj.getClass())
	    return false;
	Order other = (Order) obj;
	return Objects.equals(orderId, other.orderId) && Objects.equals(productId, other.productId);
    }

    @Override
    public String toString() {
	return "Order [orderId=" + orderId + ", productId=" + productId + ", productQuantity=" + productQuantity
		+ ", description=" + description + ", orderPlacedTimestamp=" + orderPlacedTimestamp
		+ ", orderUpdatedTimestamp=" + orderUpdatedTimestamp + "]";
    }

}
